#!/usr/bin/with-contenv bash

export JELLYFIN_DATA_DIR="/config/data" \
JELLYFIN_CONFIG_DIR="/config" \
JELLYFIN_LOG_DIR="/config/log" \
JELLYFIN_CACHE_DIR="/config/cache"

if [ -n "${UMASK_SET}" ] && [ -z "${UMASK}" ]; then
  echo -e "You are using a legacy method of defining umask\nplease update your environment variable from UMASK_SET to UMASK\nto keep the functionality after July 2021"
  umask ${UMASK_SET}
fi

exec \
	s6-setuidgid abc /usr/bin/jellyfin \
	--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg \
	--webdir=/usr/share/jellyfin/web
