#!/usr/bin/with-contenv bash

# create directories
mkdir -p \
    /config/{log,data/transcodes,cache} \
    /data \
    /transcode

# permissions
find /config \
     /config/* \
     /config/data/transcodes \
     /transcode \
     \( ! -user abc -o ! -group abc \) \
     -exec chown abc:abc {} +
