#!/usr/bin/with-contenv bash

# create directories
mkdir -p \
	/config/{log,data,cache} \
	/data \
	/transcode

# permissions
chown abc:abc \
	/config \
	/config/* \
	/data \
	/transcode
if [ -n "$(ls -A /data 2>/dev/null)" ]; then
chown abc:abc \
	/data/*
fi
