#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*             This image is deprecated.              *
*      We will not offer support for this image      *
*             and it will not be updated.            *
*                                                    *
*                                                    *
******************************************************
******************************************************

The "bionic" tag has been deprecated.
Please use the "latest" tag instead.


******************************************************
******************************************************'
